all: 
	gcc -g ./main.c ./src/LinkedList.c ./src/InteractFuncs.c ./src/Interactive.c ./src/Command.c -o ./main.exe 
	valgrind -s ./main.exe < test.txt
# Livers.txt 3 21 Rybin Vladimir Victorovich 6 2 2007 M 1000.0 4 33 Makarova Svetlana 24 11 1982 W 3850.95 6
# Livers.txt 3 21 Rybin Vladimir Victorovich 6 2 2007 M 1000.0 6