test_str:
	gcc -o ./tests/test_str.exe ./tests/string_test.c
	valgrind --leak-check=full ./tests/test_str.exe

test_int:
	gcc -o ./tests/test_int.exe ./tests/int_test.c
	valgrind --leak-check=full ./tests/test_int.exe